#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'

require 'netlinx/parser/lexer'
require 'netlinx/parser/nodes'

module NetLinx
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 128)

  def initialize data, ignore_comments: true
    @data = data
    @ignore_comments = ignore_comments
    
    @lexer = NetLinx::Lexer.new data
    # Convert all token names to uppercase.
    @tokens = @lexer.run.map! { |t| [t[0].upcase, t[1]] }
  end
  
  def parse
    do_parse
  end
  
  def next_token
    @tokens.shift
  end
  
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    27,    50,    51,    52,    53,     4,    28,    29,    30,    31,
    32,    33,    34,    35,    36,    37,    50,    51,    52,    53,
    50,    51,    52,    53,    55,    48,    54,    47,    46,    45,
    44,    43,    10,    11,    12,    42,    13,    41,    14,    15,
    16,    17,    18,    19,     5,    21,    22,    23,    24,    25,
    27,    40,    38,    58,    59,     4,    28,    29,    30,    31,
    32,    33,    34,    35,    36,    37,    60,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    10,    11,    12,   nil,    13,   nil,    14,    15,
    16,    17,    18,    19,     5,    21,    22,    23,    24,    25 ]

racc_action_check = [
     0,    48,    48,    48,    48,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    43,    43,    43,    43,
    47,    47,    47,    47,    46,    42,    46,    42,    41,    40,
    38,    27,     0,     0,     0,    26,     0,    20,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     2,     5,     1,    55,    56,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    58,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     2,     2,     2,   nil,     2,   nil,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2 ]

racc_action_pointer = [
    -2,    52,    48,   nil,   nil,   -15,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   -31,   nil,   nil,   nil,   nil,   nil,    33,   -35,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    30,   nil,
    23,    26,   -41,    13,   nil,   nil,   -43,    17,    -2,   nil,
   nil,   nil,   nil,   nil,   nil,    51,   -15,   nil,    -3,   nil,
   nil ]

racc_action_default = [
    -2,   -48,    -1,    -4,    -6,   -48,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -20,   -21,
   -48,   -24,   -25,   -26,   -27,   -28,   -48,   -48,   -34,   -35,
   -36,   -37,   -38,   -39,   -40,   -41,   -42,   -43,   -48,    -3,
   -48,   -48,   -29,   -48,    61,    -7,   -48,   -48,   -48,   -32,
   -44,   -45,   -46,   -47,   -22,   -48,   -48,   -31,   -48,   -30,
   -23 ]

racc_goto_table = [
    49,     3,     2,    39,    56,    57,     1 ]

racc_goto_check = [
    10,     3,     2,     3,    10,    10,     1 ]

racc_goto_pointer = [
   nil,     6,     2,     1,   nil,   nil,   nil,   nil,   nil,   nil,
   -43,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     6,     7,     8,     9,    20,    26,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 71, :_reduce_1,
  0, 71, :_reduce_2,
  2, 72, :_reduce_3,
  1, 72, :_reduce_4,
  0, 72, :_reduce_5,
  1, 73, :_reduce_6,
  3, 73, :_reduce_7,
  1, 73, :_reduce_8,
  1, 73, :_reduce_none,
  1, 73, :_reduce_none,
  1, 73, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  1, 74, :_reduce_none,
  4, 75, :_reduce_22,
  6, 75, :_reduce_23,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  1, 78, :_reduce_none,
  2, 76, :_reduce_29,
  5, 76, :_reduce_30,
  4, 76, :_reduce_31,
  3, 77, :_reduce_32,
  0, 81, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 79, :_reduce_none,
  1, 80, :_reduce_44,
  1, 80, :_reduce_45,
  1, 80, :_reduce_46,
  1, 80, :_reduce_47 ]

racc_reduce_n = 48

racc_shift_n = 61

racc_token_table = {
  false => 0,
  :error => 1,
  :IDENTIFIER => 2,
  :DPS => 3,
  :NUMBER => 4,
  :DECIMAL => 5,
  :STRING => 6,
  :COMMENT => 7,
  :CHAR => 8,
  :WIDECHAR => 9,
  :INTEGER => 10,
  :SINTEGER => 11,
  :LONG => 12,
  :SLONG => 13,
  :FLOAT => 14,
  :DOUBLE => 15,
  :DEV => 16,
  :DEVCHAN => 17,
  :IF => 18,
  :ELSE => 19,
  :SELECT => 20,
  :ACTIVE => 21,
  :SWITCH => 22,
  :CASE => 23,
  :FOR => 24,
  :WHILE => 25,
  :MEDIUM_WHILE => 26,
  :LONG_WHILE => 27,
  :BREAK => 28,
  :DEFAULT => 29,
  :RETURN => 30,
  :DEFINE_CALL => 31,
  :DEFINE_COMBINE => 32,
  :DEFINE_CONNECT_LEVEL => 33,
  :DEFINE_CONSTANT => 34,
  :DEFINE_DEVICE => 35,
  :DEFINE_EVENT => 36,
  :DEFINE_FUNCTION => 37,
  :DEFINE_LATCHING => 38,
  :DEFINE_MODULE => 39,
  :DEFINE_MUTUALLY_EXCLUSIVE => 40,
  :DEFINE_PROGRAM => 41,
  :DEFINE_START => 42,
  :DEFINE_TOGGLING => 43,
  :DEFINE_TYPE => 44,
  :DEFINE_VARIABLE => 45,
  :PROGRAM_NAME => 46,
  :BUTTON_EVENT => 47,
  :CHANNEL_EVENT => 48,
  :DATA_EVENT => 49,
  :LEVEL_EVENT => 50,
  :REBUILD_EVENT => 51,
  "." => 52,
  "!" => 53,
  "*" => 54,
  "/" => 55,
  "+" => 56,
  "-" => 57,
  ">" => 58,
  ">=" => 59,
  "<" => 60,
  "<=" => 61,
  "==" => 62,
  "!=" => 63,
  "&&" => 64,
  "||" => 65,
  "=" => 66,
  "," => 67,
  "[" => 68,
  "]" => 69 }

racc_nt_base = 70

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IDENTIFIER",
  "DPS",
  "NUMBER",
  "DECIMAL",
  "STRING",
  "COMMENT",
  "CHAR",
  "WIDECHAR",
  "INTEGER",
  "SINTEGER",
  "LONG",
  "SLONG",
  "FLOAT",
  "DOUBLE",
  "DEV",
  "DEVCHAN",
  "IF",
  "ELSE",
  "SELECT",
  "ACTIVE",
  "SWITCH",
  "CASE",
  "FOR",
  "WHILE",
  "MEDIUM_WHILE",
  "LONG_WHILE",
  "BREAK",
  "DEFAULT",
  "RETURN",
  "DEFINE_CALL",
  "DEFINE_COMBINE",
  "DEFINE_CONNECT_LEVEL",
  "DEFINE_CONSTANT",
  "DEFINE_DEVICE",
  "DEFINE_EVENT",
  "DEFINE_FUNCTION",
  "DEFINE_LATCHING",
  "DEFINE_MODULE",
  "DEFINE_MUTUALLY_EXCLUSIVE",
  "DEFINE_PROGRAM",
  "DEFINE_START",
  "DEFINE_TOGGLING",
  "DEFINE_TYPE",
  "DEFINE_VARIABLE",
  "PROGRAM_NAME",
  "BUTTON_EVENT",
  "CHANNEL_EVENT",
  "DATA_EVENT",
  "LEVEL_EVENT",
  "REBUILD_EVENT",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"[\"",
  "\"]\"",
  "$start",
  "program",
  "expressions",
  "expression",
  "define_section",
  "event_handler",
  "definition",
  "assignment",
  "event_handler_type",
  "type",
  "value",
  "comparison" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_1(val, _values)
     Program.new val[0] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 29)
  def _reduce_2(val, _values)
     Program.new 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_3(val, _values)
     val.flatten.compact 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_4(val, _values)
     val 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_5(val, _values)
     
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_6(val, _values)
     Comment.new(val[0]) unless @ignore_comments 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_7(val, _values)
     ProgramName.new val[2] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 41)
  def _reduce_8(val, _values)
     DefineSection.new val[0].downcase.to_sym 
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'parser.y', 62)
  def _reduce_22(val, _values)
     EventHandler.new val[0].downcase.to_sym, val[2].downcase.to_sym, nil 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_23(val, _values)
     EventHandler.new val[0].downcase.to_sym, val[2].downcase.to_sym, val[4].downcase.to_sym 
  end
.,.,

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'parser.y', 75)
  def _reduce_29(val, _values)
     Definition.new val[1], nil,    val[0].downcase.to_sym 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_30(val, _values)
     Definition.new val[1], Array.new(val[3].to_i, nil), val[0].downcase.to_sym 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_31(val, _values)
     Definition.new val[1], val[3], val[0].downcase.to_sym 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 83)
  def _reduce_32(val, _values)
     Assignment.new val[0], val[2] 
  end
.,.,

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'parser.y', 104)
  def _reduce_44(val, _values)
     DPS.new *(val[0].map &:to_i) 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 105)
  def _reduce_45(val, _values)
     val[0].to_i 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 106)
  def _reduce_46(val, _values)
     val[0].to_f 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 107)
  def _reduce_47(val, _values)
     val[0].to_s 
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module NetLinx
